[build]
publish = "build/"
command = "lektor build --output-path ./build"
environment = { PYTHON_VERSION = 3.8 }

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"

  [headers.values]
  Content-Security-Policy = ""